name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GPG
      run: brew install gpg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Decrypt large secret
      run: bash ./provisioning/import_provisioning.sh
      env:
        DECRYPTION_PASSWORD: ${{ secrets.DECRYPTION_PASSWORD }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: xcodebuild -sdk iphoneos -project Tim-Bak-Toe.xcodeproj -configuration Release -scheme XO3 -derivedDataPath DerivedData -archivePath DerivedData/Archive/XO3 archive
    - name: Export Archive
      run: xcodebuild -exportArchive -archivePath DerivedData/Archive/XO3.xcarchive -exportOptionsPlist provisioning/App-Store.plist -exportPath DerivedData/ipa
    - name: Dump file hierarchy
      run: ls -R
    - name: Deploy App to Apple
      run: xcrun altool --upload-app --type ios --file DerivedData/ipa/XO3.ipa --username "${{ secrets.appstore_connect_username }}" --password "${{ secrets.appstore_connect_password }}" --verbose
